### ISSUE TITLE
I don't see named outlet support. Is that worthwhile?

### ISSUE THREAD

**Issue by arturohernandez10** [arnelenero/react-router-outlet#3]
Please if I am mistaken let me know. I may just send you a pull request for it. Yes, it appear as if Angular has a bad rep among React users.

**Comment by arnelenero** [comment]
Hi. Are you thinking of using multiple outlets in the same component? Is this the reason why you are exploring named outlet support?

I'm interested to see an example of the intended syntax,  Thanks.

**Comment by arturohernandez10** [comment]
It was an option. But now I think it is less likely. If we come back to it, I'll post a sample here.
